
#include "ligaturize.h"

#include "charArray_substringUtility.h"

#define VOICELESS_ALVEOLAR_AFFRICATE_L "t͡s"
#define VOICELESS_ALVEOLAR_AFFRICATE_S "ʦ"

#define VOICELESS_POSTALVEOLAR_AFFRICATE_L "t͡ʃ"
#define VOICELESS_POSTALVEOLAR_AFFRICATE_S "ʧ"

#define VOICELESS_ALVEOLO_PALATAL_AFFRICATE_L "t͡ɕ"
#define VOICELESS_ALVEOLO_PALATAL_AFFRICATE_S "ʨ"

#define VOICED_ALVEOLAR_AFFRICATE_L "d͡z"
#define VOICED_ALVEOLAR_AFFRICATE_S "ʣ"

#define VOICED_POSTALVEOLAR_AFFRICATE_L "d͡ʒ"
#define VOICED_POSTALVEOLAR_AFFRICATE_S "ʤ"

#define VOICED_ALVEOLO_PALATAL_AFFRICATE_L "d͡ʑ"
#define VOICED_ALVEOLO_PALATAL_AFFRICATE_S "ʥ"

void ligaturize(struct charArray* var)
{
    charArray_substringUtility_replace(charArray, 
    VOICELESS_ALVEOLAR_AFFRICATE_L, sizeof(VOICELESS_ALVEOLAR_AFFRICATE_L),
    VOICELESS_ALVEOLAR_AFFRICATE_S, sizeof(VOICELESS_ALVEOLAR_AFFRICATE_S));

    charArray_substringUtility_replace(charArray, 
    VOICELESS_POSTALVEOLAR_AFFRICATE_L, sizeof(VOICELESS_POSTALVEOLAR_AFFRICATE_L),
    VOICELESS_POSTALVEOLAR_AFFRICATE_S, sizeof(VOICELESS_POSTALVEOLAR_AFFRICATE_S));

    charArray_substringUtility_replace(charArray, 
    VOICELESS_ALVEOLO_PALATAL_AFFRICATE_L, sizeof(VOICELESS_ALVEOLO_PALATAL_AFFRICATE_L),
    VOICELESS_ALVEOLO_PALATAL_AFFRICATE_S, sizeof(VOICELESS_ALVEOLO_PALATAL_AFFRICATE_S));

    charArray_substringUtility_replace(charArray, 
    VOICED_ALVEOLAR_AFFRICATE_L, sizeof(VOICED_ALVEOLAR_AFFRICATE_L),
    VOICED_ALVEOLAR_AFFRICATE_S, sizeof(VOICED_ALVEOLAR_AFFRICATE_S));

    charArray_substringUtility_replace(charArray, 
    VOICED_POSTALVEOLAR_AFFRICATE_L, sizeof(VOICED_POSTALVEOLAR_AFFRICATE_L),
    VOICED_POSTALVEOLAR_AFFRICATE_S, sizeof(VOICED_POSTALVEOLAR_AFFRICATE_S));

    charArray_substringUtility_replace(charArray, 
    VOICED_ALVEOLO_PALATAL_AFFRICATE_L, sizeof(VOICED_ALVEOLO_PALATAL_AFFRICATE_L),
    VOICED_ALVEOLO_PALATAL_AFFRICATE_S, sizeof(VOICED_ALVEOLO_PALATAL_AFFRICATE_S));
}
